### ISSUE TITLE
`.action{/* 注释 */}` 格式化时，`{` 与 `/` 、`/` 与 `}` 之间不能增加空格

### ISSUE THREAD

**Issue by TCOTC** [frostime/sy-test-template#2]
- `.action{/* 注释 */}` 不能变成 `.action{ /* 注释 */ }`
-  `{{/* 注释 */}}` 不能变成 `{{ /* 注释 */ }}`

**Comment by frostime** [comment]
这个影响好像不大吧？算bug吗？

**Comment by TCOTC** [comment]
增加空格之后就运行不了了，会报错
